name: Test Backend

on:
  push:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest

    env:
      RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Test backend imports and Riot API key
        run: |
          python - <<EOF
import os
import sys
sys.path.append('backend')
import riot_api
import insights
import aws_ai

if os.getenv('RIOT_API_KEY'):
    print('Riot API key loaded successfully!')
else:
    print('Riot API key NOT found!')
    sys.exit(1)
EOF
