name: Deploy Backend to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Install backend dependencies
      - name: Install requirements
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run backend tests
      - name: Run backend tests
        run: |
          cd backend
          python test_backend.py

      # 5. Zip backend code (flattened, no extra backend folder)
      - name: Zip backend code
        run: |
          cd backend
          zip -r ../backend.zip . -x "*.pyc"

      # 6. Upload zip to S3
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 cp ../backend.zip s3://lens-of-legends-backend-s3/backend.zip

      # 7. Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'lens-of-legends-backend'
          environment_name: 'Lens-of-legends-backend-env'
          region: 'ap-southeast-2'
          version_label: 'v${{ github.run_number }}'
          bucket_name: ${{ secrets.S3_BUCKET }}
          file: 'backend.zip'
          wait_for_deployment: true

