name: Deploy Backend to S3

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r backend/requirements.txt

    - name: Create backend.zip
      run: |
        zip -r backend/backend.zip backend/*

    - name: Upload to S3
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload backend.zip to S3
      run: |
        aws s3 cp backend.zip s3://${{ secrets.S3_BUCKET }}/backend.zip
