name: Deploy Backend to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python (if your backend is Python)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # change to your version

      # 3. Install dependencies (optional, good for testing)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Zip backend code
      - name: Zip backend
        run: zip -r backend.zip . -x "*.git*"

      # 5. Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          application_name: lens-of-legends-backend
          environment_name: Lens-of-legends-backend-env-1
          version_label: ${{ github.run_number }}
          region: ${{ secrets.AWS_REGION }}
          bucket_name: lens-of-legends-backend-deploy
          bucket_key: backend.zip
          deployment_package: backend.zip
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          wait_for_deployment: true
